[versions]
ktor = "2.0.3"

[libraries.ktor-client-core]
version.ref = "ktor"
module = "io.ktor:ktor-client-core"

[libraries.ktor-serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.ktor-client-contentnegotiation]
version.ref = "ktor"
module = "io.ktor:ktor-client-content-negotiation"

[libraries.ktor-client-okhttp]
version.ref = "ktor"
module = "io.ktor:ktor-client-okhttp"

[libraries.ktor-client-js]
version.ref = "ktor"
module = "io.ktor:ktor-client-js"
